### ISSUE TITLE
Using DownloadButton will cause *all* UIButtons with a tintColor be shown with a border

### ISSUE THREAD

**Issue by kennytm** [PavelKatunin/DownloadButton#11]
In `UIButton+PKDownloadButton.m`, the `-tintColorDidChange` method is reimplemented. This replaced the default implementation of the said method, and makes **all** UIButtons without a custom `-tintColorDidChange` to gain the rounded border whenever their `tintColor` is changed. 

It is better to create a UIButton subclass for the "startDownloadButton" and "downloadedButton" and override `-tintColorDidChange` in the subclass to avoid the global effect.

**Comment by dusek** [comment]
I guess this can be closed since it seems to be fixed by #12 :wink:

**Comment by kennytm** [comment]
Fixed in #12. I wonder why GitHub doesn't automatically close this :smile:

**Comment by markst** [comment]
This doesn't seem to be resolved. https://github.com/PavelKatunin/DownloadButton/pull/12#issuecomment-353229011
