### ISSUE TITLE
Can't seem to change the start download button title (SWIFT)

### ISSUE THREAD

**Issue by cyrilzakka** [PavelKatunin/DownloadButton#13]
Hey,
So I added your button to my table view in IB and created an IB outlet but when I try changing the start download title in `viewDidLoad`, nothing happens at all.
`downloadButton.startDownloadButton.setTitle("Hello", forState: .Normal)`
`downloadButton.startDownloadButton.titleLabel?.text = "GET"`

**Comment by whisper-bye** [comment]
+1 @PavelKatunin 

``` SWIFT
let downloadButton = PKDownloadButton()

downloadButton.downloadedButton!.setTitle("DELETE", forState: .Normal)
downloadButton.downloadedButton!.setTitleColor(UIColor.redColor(), forState: .Normal)
```

**Comment by cyrilzakka** [comment]
Yeah your code doesn't change the title either :(

**Comment by whisper-bye** [comment]
yeah, we need some of the swift code samples
waiting for author （╯＿╰）

**Comment by whisper-bye** [comment]
@Archivus 
finally i figured it out..

``` swift
let attributedString =
    NSAttributedString(string: "INSTALL", attributes: [NSForegroundColorAttributeName : UIColor.greenColor()])

downloadButton.startDownloadButton!.setAttributedTitle(attributedString, forState: .Normal)
```

**Comment by cyrilzakka** [comment]
@whisper-bye Thank you very much, I'll try it out!

**Comment by cyrilzakka** [comment]
@whisper-bye worked perfectly! Should I keep this open?

**Comment by whisper-bye** [comment]
@Archivus 
whatever~

**Comment by ryanholden8** [comment]
#16 addresses this issue

**Comment by whisper-bye** [comment]
@ryanholden8 
It didn't work for me

**Comment by ryanholden8** [comment]
Did you use `updateDownloadedButtonText` or `updateStartDownloadButtonText` ? A code example of what is not working would allow me to be helpful. :)

@whisper-bye

**Comment by whisper-bye** [comment]
@ryanholden8 
I can not find the function signature, please show me some case, like rewrite the following code
```swift
let attributedString =
    NSAttributedString(string: "INSTALL", attributes: [NSForegroundColorAttributeName : UIColor.greenColor()])

downloadButton.startDownloadButton!.setAttributedTitle(attributedString, forState: .Normal)
```
by using updateDownloadedButtonText or updateStartDownloadButtonText

**Comment by ryanholden8** [comment]
@whisper-bye Gotcha, the methods are defined in the code changes within the PR. Here is an example: (Using Swift 3)

```
downloadButton.updateStartDownloadButtonText("INSTALL")
downloadButton.startDownloadButton.tintColor = .green
```

**Comment by whisper-bye** [comment]
@ryanholden8 
I will check it out later, thanks for your quick reply
