### ISSUE TITLE
Updating DownloadButton in a cell while scrolling

### ISSUE THREAD

**Issue by ghost** [PavelKatunin/DownloadButton#14]
Hi,

Thanks for this awesome component. 
I have a situation where I have added a DownloadButton to each row of a UITableView. Imagine I tap on one of them and a download starts and the button gets updated when the download progresses. Now If I scroll, the cells get reused. How can I restore the state of each DownloadButton? (Showing download progress to be exact)

**Comment by dusek** [comment]
Unless I misunderstand, this is beyond scope of `DownloadButton`, but rather a concern for the controller (but I do understand this question can arise a lot when using `DownloadButton`, as I had to tackle it myself too).

One way which I would consider clean is to create a `UIViewController` (e.g. a `DownloadButtonController`) which listens to model changes (including download progress), and then translates them to changes in the button (`DownloadButtonController.view`). Then you could use [this technique](http://khanlou.com/2015/04/view-controllers-in-cells/) to embed the view controller (and its view) in the `UITableViewCell`.
