### ISSUE TITLE
Support for iOS 7

### ISSUE THREAD

**Issue by billburgess** [PavelKatunin/DownloadButton#3]
Is there any reason support for iOS 7 can't be added? It would be helpful since the button changes were made back in 7 and continue in 8.

**Comment by PavelKatunin** [comment]
Thanks, good point.

**Comment by billburgess** [comment]
Would be helpful. Thanks for considering it.

**Comment by onekiloparsec** [comment]
The support for iOS7 is really dead simple, the button already works in iOS7. I've made a pull request for making it easy for you: just click. :-) 
[Pull Request #5](https://github.com/PavelKatunin/DownloadButton/pull/5)

**Comment by PavelKatunin** [comment]
Thank you, guys!
